trigger:
- master
- staging

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    imageTag: $(Build.BuildNumber)
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    imageTag: $(Build.BuildNumber)-staging

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: checkout
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore -c Release'

- task: DotNetCoreCLI@2
  displayName: tests
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: '--no-restore'

- task: Docker@2
  displayName: docker
  inputs:
    containerRegistry: 'docker'
    repository: 'fcp20/nibo-devops-challenge'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(imageTag)'
    addPipelineData: false