apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: fcp20/nibo-devops-challenge:20201109.7
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  type: LoadBalancer
  selector:
    app: mywebapp
  ports:
    - port: 80
      targetPort: 8081
